#!/usr/bin/env python3
"""Emit `agents/openai.yaml` for every skill that is explicit-invocation only.

Claude Code honours `disable-model-invocation: true` in SKILL.md frontmatter.
Codex ignores that field — its plugin validator actively rejects it when true —
and reads `<skill>/agents/openai.yaml` with `policy.allow_implicit_invocation`
instead, the shape its own bundled skills use. Shipping both keeps one skill
tree behaving the same way on both harnesses.

`interface.display_name` and `interface.short_description` are required
non-empty by that validator, so both are derived here from the skill's own
frontmatter. SUMMARY holds a hand-written line for any skill whose description
opens with a trigger list rather than a statement of what it does.

Run after adding a skill or editing a description; idempotent.

    scripts/sync_codex_policy.py           write and report
    scripts/sync_codex_policy.py --check   exit 1 if anything is missing or stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

SKILLS = Path(__file__).resolve().parent.parent / "skills"
STAMP = "# generated by scripts/sync_codex_policy.py — do not hand-edit\n"

# Skills whose `description` opens with trigger words ("Use for …", "Apply
# when …"). A trigger list is the wrong text for a UI label, so these carry a
# written summary instead.
SUMMARY: dict[str, str] = {
    "arena": "Run the same task on several models in parallel, then judge the candidates",
    "architect": "Panel of independent design proposals for one problem, then a synthesis",
    "automate-me": "Mine your own transcripts into a personal mode skill",
    "blast-radius": "Map everything a proposed change can reach before making it",
    "bro": "Terse, high-signal replies with no preamble",
    "create-verification-skill": "Generate a project-local skill that drives the real app for proof",
    "figure-it-out": "Push through an unclear problem without asking the human to unblock you",
    "how": "Explain how a subsystem works, and where new code belongs in it",
    "interrogate": "Adversarial multi-reviewer stress test of a change or a design",
    "maintain-verification-skill": "Keep an existing verify-* skill current with the app",
    "no-comments": "Strip comments that restate the code",
    "rigor": "Concise replies, deliberate subagents, simple code, verified work",
    "recall": "Search past session transcripts for what was decided and why",
    "reflect": "Review a finished session for lessons worth encoding in a skill",
    "show-me-your-work": "Keep an auditable decision trail through a long autonomous run",
    "swarm": "Fan out parallel independent verifiers and aggregate one verdict",
    "tdd": "Write the failing test first, then the code that passes it",
    "teach": "Explain a concept at the depth the asker actually needs",
    "technical-writing": "Structure technical prose so a reader finds the answer fast",
    "typescript-best-practices": "TypeScript idioms to apply when reading or editing .ts/.tsx",
    "unslop": "Cut AI tells from any writing",
    "why": "Recover the rationale behind a decision from the evidence trail",
}

# Readable display names where title-casing the slug gets it wrong.
DISPLAY: dict[str, str] = {
    "typescript-best-practices": "TypeScript best practices",
    "rigor": "Rigor mode",
    "tdd": "TDD",
    "principle-migrate-callers-then-delete-legacy-apis": "Principle: migrate callers, then delete legacy APIs",
    "principle-type-system-discipline": "Principle: type-system discipline",
    "principle-guard-the-context-window": "Principle: guard the context window",
    "principle-never-block-on-the-human": "Principle: never block on the human",
    "principle-outcome-oriented-execution": "Principle: outcome-oriented execution",
    "principle-redesign-from-first-principles": "Principle: redesign from first principles",
    "principle-separate-before-serializing-shared-state": "Principle: separate before serializing shared state",
}


def frontmatter(text: str) -> dict[str, str]:
    """Read the scalar frontmatter keys. Values may be quoted or folded."""
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end == -1:
        return {}
    out: dict[str, str] = {}
    key = None
    for line in text[4:end].splitlines():
        m = re.match(r"^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$", line)
        if m:
            key, value = m.group(1), m.group(2).strip()
            out[key] = value
        elif key and line.startswith((" ", "\t")):
            out[key] = (out[key] + " " + line.strip()).strip()
    return out


def unquote(value: str) -> str:
    """Undo the frontmatter's own quoting so the text reads as prose."""
    value = value.strip()
    for block in (">-", ">", "|-", "|"):
        if value == block:
            return ""
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        inner = value[1:-1]
        return inner.replace('\\"', '"') if value[0] == '"' else inner.replace("''", "'")
    return value.replace('\\"', '"')


def summarize(name: str, description: str, limit: int = 96) -> str:
    if name in SUMMARY:
        return SUMMARY[name]
    text = re.sub(r"\s+", " ", unquote(description)).strip()
    if not text:
        return name.replace("-", " ")
    first = re.split(r"(?<=[.!?])\s", text, maxsplit=1)[0].rstrip(".")
    if len(first) > limit:
        first = first[: limit - 1].rsplit(" ", 1)[0]
    return first


def display(name: str) -> str:
    if name in DISPLAY:
        return DISPLAY[name]
    if name.startswith("principle-"):
        rest = name[len("principle-") :].replace("-", " ")
        return "Principle: " + rest
    words = name.replace("-", " ")
    return words[0].upper() + words[1:]


def yaml_single(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render(name: str, description: str) -> str:
    return (
        STAMP
        + "interface:\n"
        f"  display_name: {yaml_single(display(name))}\n"
        f"  short_description: {yaml_single(summarize(name, description))}\n"
        f"  default_prompt: {yaml_single(f'Use ${name} as the user asked.')}\n"
        "policy:\n"
        "  allow_implicit_invocation: false\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report drift, write nothing")
    args = ap.parse_args()

    written, stale, implicit = [], [], []
    for skill_md in sorted(SKILLS.glob("*/SKILL.md")):
        fm = frontmatter(skill_md.read_text(encoding="utf-8"))
        slug = skill_md.parent.name
        name = fm.get("name") or slug
        out = skill_md.parent / "agents" / "openai.yaml"

        if fm.get("disable-model-invocation", "").lower() != "true":
            implicit.append(name)
            if out.is_file() and STAMP in out.read_text(encoding="utf-8"):
                stale.append(f"{name}: has a generated openai.yaml but is implicitly invocable")
            continue

        body = render(slug, fm.get("description", ""))
        current = out.read_text(encoding="utf-8") if out.is_file() else None
        if current == body:
            continue
        if args.check:
            stale.append(f"{name}: {'missing' if current is None else 'out of date'}")
            continue
        out.parent.mkdir(exist_ok=True)
        out.write_text(body, encoding="utf-8")
        written.append(name)

    print(f"skill interface files:     {len(list(SKILLS.glob('*/agents/openai.yaml')))}")
    print(f"implicitly invocable:       {len(implicit)} ({', '.join(implicit) or 'none'})")
    if written:
        print(f"wrote: {len(written)}")
    if stale:
        print("\nDRIFT:")
        for line in stale:
            print(f"  {line}")
        return 1
    print("policy files match SKILL.md frontmatter")
    return 0


if __name__ == "__main__":
    sys.exit(main())
