#!/usr/bin/env python3
"""Emit `agents/openai.yaml` for every skill that is explicit-invocation only.

Claude Code honours `disable-model-invocation: true` in SKILL.md frontmatter.
Codex ignores that field — its plugin validator actively rejects it when true —
and reads `<skill>/agents/openai.yaml` with `policy.allow_implicit_invocation`
instead, the shape its own bundled skills use. Shipping both keeps one skill
tree behaving the same way on both harnesses.

`interface.display_name` and `interface.short_description` are required
non-empty by that validator, so both are derived here from the skill's own
frontmatter.

Run after adding a skill or editing a description; idempotent.

    scripts/sync_codex_policy.py           write and report
    scripts/sync_codex_policy.py --check   exit 1 if anything is missing or stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

SKILLS = Path(__file__).resolve().parent.parent / "skills"
STAMP = "# generated by scripts/sync_codex_policy.py — do not hand-edit\n"


def vendored_policy_error(fm: dict[str, str], policy: Path) -> str | None:
    """Check the block-style invocation flag without rewriting upstream metadata."""
    explicit = fm.get("disable-model-invocation", "").lower() == "true"
    if not policy.is_file():
        return "explicit-only skill needs agents/openai.yaml" if explicit else None
    text = policy.read_text(encoding="utf-8")
    block = re.search(r"^policy:[ \t]*(?:#.*)?\n((?:[ \t]+[^\n]*\n|\n)*)", text + "\n", re.M)
    flag = re.search(r"^ +allow_implicit_invocation: *(true|false) *(?:#.*)?$", block[1], re.M) if block else None
    if explicit and (not flag or flag[1] != "false"):
        return "explicit-only skill needs policy.allow_implicit_invocation: false (block YAML)"
    return None

def frontmatter(text: str) -> dict[str, str]:
    """Read the scalar frontmatter keys. Values may be quoted or folded."""
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end == -1:
        return {}
    out: dict[str, str] = {}
    key = None
    for line in text[4:end].splitlines():
        m = re.match(r"^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$", line)
        if m:
            key, value = m.group(1), m.group(2).strip()
            out[key] = value
        elif key and line.startswith((" ", "\t")):
            out[key] = (out[key] + " " + line.strip()).strip()
    return out


def unquote(value: str) -> str:
    """Undo the frontmatter's own quoting so the text reads as prose."""
    value = value.strip()
    for block in (">-", ">", "|-", "|"):
        if value == block:
            return ""
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        inner = value[1:-1]
        return inner.replace('\\"', '"') if value[0] == '"' else inner.replace("''", "'")
    return value.replace('\\"', '"')


def summarize(name: str, description: str, limit: int = 96) -> str:
    text = re.sub(r"\s+", " ", unquote(description)).strip()
    if not text:
        return name.replace("-", " ")
    first = re.split(r"(?<=[.!?])\s", text, maxsplit=1)[0].rstrip(".")
    if len(first) > limit:
        first = first[: limit - 1].rsplit(" ", 1)[0]
    return first


def display(name: str) -> str:
    words = name.replace("-", " ")
    return words[0].upper() + words[1:]


def yaml_single(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render(name: str, description: str) -> str:
    return (
        STAMP
        + "interface:\n"
        f"  display_name: {yaml_single(display(name))}\n"
        f"  short_description: {yaml_single(summarize(name, description))}\n"
        f"  default_prompt: {yaml_single(f'Use ${name} as the user asked.')}\n"
        "policy:\n"
        "  allow_implicit_invocation: false\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report drift, write nothing")
    args = ap.parse_args()

    manifest = SKILLS.parent / "vendor.json"
    vendored = {e["name"] for e in json.loads(manifest.read_text())["skills"]} if manifest.exists() else set()
    written, stale, implicit = [], [], []
    for skill_md in sorted(SKILLS.glob("*/SKILL.md")):
        fm = frontmatter(skill_md.read_text(encoding="utf-8"))
        slug = skill_md.parent.name
        name = fm.get("name") or slug
        out = skill_md.parent / "agents" / "openai.yaml"

        if slug in vendored:
            error = vendored_policy_error(fm, out)
            if error:
                stale.append(f"{name}: {error}; fix through a vendor patch or sync")
            continue

        if fm.get("disable-model-invocation", "").lower() != "true":
            implicit.append(name)
            if out.is_file() and STAMP in out.read_text(encoding="utf-8"):
                stale.append(f"{name}: has a generated openai.yaml but is implicitly invocable")
            continue

        body = render(slug, fm.get("description", ""))
        current = out.read_text(encoding="utf-8") if out.is_file() else None
        if current == body:
            continue
        if args.check:
            stale.append(f"{name}: {'missing' if current is None else 'out of date'}")
            continue
        out.parent.mkdir(exist_ok=True)
        out.write_text(body, encoding="utf-8")
        written.append(name)

    print(f"skill interface files:     {len(list(SKILLS.glob('*/agents/openai.yaml')))}")
    print(f"implicitly invocable:       {len(implicit)} ({', '.join(implicit) or 'none'})")
    if written:
        print(f"wrote: {len(written)}")
    if stale:
        print("\nDRIFT:")
        for line in stale:
            print(f"  {line}")
        return 1
    print("policy files match SKILL.md frontmatter")
    return 0


if __name__ == "__main__":
    sys.exit(main())
